name: CI
run-name: ${{ github.actor }}

on: push

jobs:
  build:
    if: github.actor == 'azimafroozeh'
    strategy:
      fail-fast: false
      matrix:
        platform: [ self-hosted ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Make directory build
        run: mkdir ${{github.workspace}}/build

      - name: nvidia-smi
        run: nvidia-smi

      - name: nvcc version
        run: nvcc --version

      - name: gcc --version
        run: gcc --version

      - name: make clean
        run: make clean

      - name: mkdir -p bin/bench
        run: mkdir -p bin/bench

      - name: make bench/gen bench/gen_d1 bench/gen_d2
        run: make bench/gen bench/gen_d1 bench/gen_d2

      - name: ./bin/bench/gen <num_bits>
        run: ./bin/bench/gen 3

      - name: ./bin/bench/gen_d1 <num_bits>
        run: ./bin/bench/gen_d1 3

      - name: ./bin/bench/gen_d2 <num_bits>
        run: ./bin/bench/gen_d2 3

      - name: make directory build
        run: mkdir -p ${{github.workspace}}/build

      - name: make bench/binpack
        run: make bench/binpack

      - name: make bench/deltabinpack
        run: make bench/deltabinpack

      - name: For SSB columns
        run: |
          mkdir -p bin/ssb
          make ssb/binpack
          make ssb/deltabinpack
          make ssb/rlebinpack

      - name: encode columns
        run: ./compress.sh

      #      - name: ./bin/bench/binpack <num_bits>
      #        run: ./bin/bench/binpack 3
      #
      #      - name: ./bin/bench/binpack <num_bits>
      #        run: ./bin/bench/deltabinpack 3

      # generate dataset
      #      - name: cd test/
      #        run: |
      #          cd test/
      #          cd ssb/dbgen
      #          make
      #          cd ../loader
      #          make
      #          cd ../../
      #          python3 util.py ssb 10 gen
      #          sudo python3 util.py ssb 10 transform
      #          cd src/ssb/


      - name: mkdir -p obj/ssb
        run: mkdir -p obj/ssb

      - name: mkdir -p bin/ssb
        run: mkdir -p bin/ssb

      - name: make bin/ssb/test_perf_rle
        run: make bin/ssb/test_perf_rle

      - name: ./bin/ssb/test_perf_rle <col_name>
        continue-on-error: true
        run: ./bin/ssb/test_perf_rle lo_orderkey

      - name: ./bin/ssb/test_match_rle <col_name>
        continue-on-error: true
        run: ./bin/ssb/test_match_rle lo_orderkey

      - name: make queries
        run: |
          make bin/ssb/q11r
          make bin/ssb/q21r
          make bin/ssb/q31r
          make bin/ssb/q41r

      - name: ls /home/ubuntu/gpu-compression/test/ssb/data/s10_columnar/
        run: ls /home/ubuntu/gpu-compression/test/ssb/data/s10_columnar/

      - name: run all queries
        run: |
          ./bin/ssb/q11r
          ./bin/ssb/q21r
          ./bin/ssb/q31r
          ./bin/ssb/q41r






